### ISSUE TITLE
Segmentation Fault With Default Trace Sampler (ProbabilitySampler)

### ISSUE THREAD

**Issue by asutoshpalai** [wavefrontHQ/opencensus-exporter#4]
I directly implemented the sample code for gRPC integration for both tracing and metrics from [https://opencensus.io/guides/grpc/go/](https://opencensus.io/guides/grpc/go/) with only two changes, replacing the exporter with Wavefront and removing `trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})`. In this case, now the `ProbabilitySampler` is being used. 

With a decent probability the first trace is not sampled which doesn't set `ExemplarsPerBucket` and this makes the Wavefront exporter to crash at [wavefront/view.go:120 ](https://github.com/wavefrontHQ/opencensus-exporter/blob/983d7cdaceaf82af47b3f32a7d95f2e1a8beb710/wavefront/view.go#L120).

```go
		case c == 1:
			m = agg.ExemplarsPerBucket[i].Value
```

This bug almost practically prevents this to be used in any production environment.

As a slight deeper dive into the code, at `go.opencensus.io/stats/view/aggregation_data.go:190` we have

```go
func (a *DistributionData) addToBucket(v float64, attachments map[string]interface{}, t time.Time) {
...
	if exemplar := getExemplar(v, attachments, t); exemplar != nil {
		a.ExemplarsPerBucket[i] = exemplar
	}
}

func getExemplar(v float64, attachments map[string]interface{}, t time.Time) *metricdata.Exemplar {
	if len(attachments) == 0 {
		return nil
	}
...
}
```

The `attachments` are not set when the trace is not sampled as per the code at [go.opencensus.io/plugin/ocgrpc/stats_common.go:216](https://github.com/census-instrumentation/opencensus-go/blob/6325d764b2d4a66576c5623aa1e6010b4148a429/plugin/ocgrpc/stats_common.go#L216).

```go
func getSpanCtxAttachment(ctx context.Context) metricdata.Attachments {
	attachments := map[string]interface{}{}
...
	if spanCtx.IsSampled() {
		attachments[metricdata.AttachmentKeySpanContext] = spanCtx
	}
	return attachments
}
```

I have attached my implementation for quick reference.

[oc-wavefront-bug.zip](https://github.com/wavefrontHQ/opencensus-exporter/files/3248946/oc-wavefront-bug.zip)

**Comment by mshvol** [comment]
@asutoshpalai Sorry for the delay. Your analysis is spot on and I've identified more issues thanks to this.
