### ISSUE TITLE
`wavefront.Granularity` should me marked as a required option

### ISSUE THREAD

**Issue by asutoshpalai** [wavefrontHQ/opencensus-exporter#5]
If `wavefront.NewExporter` is called without `wavefront.Granularity` option, the created Exporter is not able to export the histogram and `Error sending histogram: histogram granularities cannot be empty` is logged in the console by wavefront-sdk-go.

This is neither documented at [OpenCensus docs](https://opencensus.io/exporters/supported-exporters/go/wavefront/) or in the [README](https://github.com/wavefrontHQ/opencensus-exporter/blob/983d7cdaceaf82af47b3f32a7d95f2e1a8beb710/README.md) of this repo.

**Comment by mshvol** [comment]
After the PR is merged, `wavefront.Granularity` is no longer a required option.
