### ISSUE TITLE
Exporter command queue and semaphore channel are *not* race-free

### ISSUE THREAD

**Issue by evantorrie** [wavefrontHQ/opencensus-exporter#7]
When running with wavefront exported in ProxySender mode with opencensus integration, there appear to be multiple race conditions exposed by `go test -race ...`.

When integrating with opencensus, the `ExportView()` or `ExportTrace()` commands are called in an opencensus `view.defaultWorker` new goroutine, separate from the goroutine which may be calling `Exporter.Flush()` or `Exporter.Stop()`.

This means that the ExportView() may run concurrently with a command such as Flush or Stop. 
 When doing so with the go race detector, I see multiple issues such as the Exporter workgroup calling `wg.Wait()` in a `Flush()` before any of the commands have been queued (via a `wg.Add()`).  This  violates the workgroup semantics that require `wg.Add()` to be called before any `wg.Wait()`.

There are also more serious race conditions related to the exporter `sem` channel, and setting it to `nil` when calling `Stop()`, while queued commands are trying to *read* that value to decide whether they should instantiate a new goroutine to execute the command.

The following test, when run with `go test -race` exposes this quite clearly.

```go
func TestProcessViewRaceCondition(tt *testing.T) {
	sender := newFake()

	fakeExp, _ := NewExporter(sender, Source("FakeSource"), AppTags(appTags), Granularity(histogram.MINUTE), DisableSelfHealth())

	wg := sync.WaitGroup{}
	wg.Add(2)
	go func() {
		defer wg.Done()
		fakeExp.processView(vd1)
	}()
	go func() {
		defer wg.Done()
		fakeExp.Stop()
	}()
	wg.Wait()
}
```

**Comment by evantorrie** [comment]
Also, just to confirm my understanding from looking at the code, it appears that the exporter workgroup `wg` and the semaphore channel `sem` are being employed to create a bounded worker pool of "sender goroutines".  If so, perhaps we should look at a more standard goroutine worker pool implementation.

**Comment by vikramraman** [comment]
Thanks for raising the issue @evantorrie ! We've addressed it as part of https://github.com/wavefrontHQ/opencensus-exporter/pull/8.
